name: build

on: [push]

jobs:
  build:
    name: windows-ironpython
    runs-on: windows-latest
    steps:
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
      - name: Install IronPython
        run: |
          choco install ironpython --version=2.7.8.1
      - name: Install dependencies
        run: |
          nuget install Grasshopper -OutputDirectory ./lib
      - name: Run
        run: |
          cd
          ipy ./componentize.py
        env:
          IRONPYTHONPATH: ./src
